from datetime import datetime, timezone
from io import BytesIO

from openpyxl import Workbook
from sqlalchemy import func, select
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.config import settings
from app.models.entities import Alert, CurrentRoomSnapshot, ReportDownload, Room, SensorFault, TemperatureReading, User


async def build_temperature_report(
    session: AsyncSession,
    start_at: datetime,
    end_at: datetime,
    room_numbers: list[int] | None,
    groups: list[str] | None,
    include_alerts: bool,
    include_faults: bool,
    generated_by: User,
) -> BytesIO:
    if start_at.tzinfo is None:
        start_at = start_at.replace(tzinfo=timezone.utc)
    if end_at.tzinfo is None:
        end_at = end_at.replace(tzinfo=timezone.utc)

    rooms_query = select(Room)
    if room_numbers:
        rooms_query = rooms_query.where(Room.room_number.in_(room_numbers))
    if groups:
        rooms_query = rooms_query.where(Room.group_code.in_(groups))
    rooms = list((await session.execute(rooms_query.order_by(Room.room_number))).scalars().all())
    room_ids = [room.id for room in rooms]
    room_by_id = {room.id: room for room in rooms}

    readings_filter = [TemperatureReading.logged_at >= start_at, TemperatureReading.logged_at <= end_at]
    if room_ids:
        readings_filter.append(TemperatureReading.room_id.in_(room_ids))
    reading_count = (await session.execute(select(func.count()).select_from(TemperatureReading).where(*readings_filter))).scalar_one()
    if reading_count > settings.api_report_max_rows:
        raise ValueError(f"report range contains {reading_count} readings; narrow the range or raise API_REPORT_MAX_ROWS")
    readings_query = select(TemperatureReading).where(*readings_filter)
    readings = list((await session.execute(readings_query.order_by(TemperatureReading.logged_at, TemperatureReading.room_id, TemperatureReading.display_label))).scalars().all())

    snapshots = []
    if room_ids:
        snapshots = list((await session.execute(select(CurrentRoomSnapshot).where(CurrentRoomSnapshot.room_id.in_(room_ids)))).scalars().all())

    alerts: list[Alert] = []
    if include_alerts:
        alerts_query = select(Alert).where(Alert.opened_at <= end_at, Alert.last_seen_at >= start_at)
        if room_ids:
            alerts_query = alerts_query.where(Alert.room_id.in_(room_ids))
        alerts = list((await session.execute(alerts_query.order_by(Alert.opened_at))).scalars().all())

    faults: list[SensorFault] = []
    if include_faults:
        faults_query = select(SensorFault).where(SensorFault.opened_at <= end_at, SensorFault.last_seen_at >= start_at)
        if room_ids:
            faults_query = faults_query.where(SensorFault.room_id.in_(room_ids))
        faults = list((await session.execute(faults_query.order_by(SensorFault.opened_at))).scalars().all())

    workbook = Workbook()
    summary = workbook.active
    summary.title = "Summary"
    summary.append(["Generated By", generated_by.email])
    summary.append(["Generated Time", datetime.now(timezone.utc).isoformat()])
    summary.append(["Timezone", "UTC"])
    summary.append(["From", start_at.isoformat()])
    summary.append(["To", end_at.isoformat()])
    summary.append(["Rooms", ", ".join(map(str, room_numbers or [])) if room_numbers else "All"])
    summary.append(["Groups", ", ".join(groups or []) if groups else "All"])
    summary.append(["Readings", len(readings)])
    summary.append(["Alerts Included", include_alerts])
    summary.append(["Sensor Faults Included", include_faults])

    snapshot_sheet = workbook.create_sheet("Room Latest Snapshot")
    snapshot_sheet.append(["Room", "Group", "Average C", "Status", "Sensor Faults", "Active Alerts", "Latest Log Time"])
    for snapshot in snapshots:
        room = room_by_id.get(snapshot.room_id)
        snapshot_sheet.append(
            [
                room.name if room else snapshot.room_id,
                room.group_code if room else None,
                snapshot.average_c,
                snapshot.status,
                snapshot.sensor_fault_count,
                snapshot.active_alert_count,
                snapshot.latest_log_time.isoformat() if snapshot.latest_log_time else None,
            ]
        )

    readings_sheet = workbook.create_sheet("Temperature Readings")
    readings_sheet.append(["Log Time", "Room", "Sensor", "Value C", "Quality", "Status"])
    for reading in readings:
        room = room_by_id.get(reading.room_id or -1)
        readings_sheet.append([reading.logged_at.isoformat(), room.name if room else reading.room_id, reading.source_tag, reading.value_c, reading.quality, reading.status])

    alert_sheet = workbook.create_sheet("Alerts")
    alert_sheet.append(["Opened At", "Last Seen", "Room ID", "Sensor ID", "Severity", "Status", "Message"])
    for alert in alerts:
        alert_sheet.append([alert.opened_at.isoformat(), alert.last_seen_at.isoformat(), alert.room_id, alert.sensor_id, alert.severity, alert.status, alert.message])

    fault_sheet = workbook.create_sheet("Sensor Faults")
    fault_sheet.append(["Opened At", "Last Seen", "Resolved At", "Room ID", "Sensor", "Fault Type", "Status", "Message"])
    for fault in faults:
        fault_sheet.append(
            [
                fault.opened_at.isoformat(),
                fault.last_seen_at.isoformat(),
                fault.resolved_at.isoformat() if fault.resolved_at else None,
                fault.room_id,
                fault.source_tag,
                fault.fault_type,
                fault.status,
                fault.message,
            ]
        )

    metadata = workbook.create_sheet("Metadata")
    metadata.append(["Key", "Value"])
    metadata.append(["Generated By", generated_by.email])
    metadata.append(["Generated Time", datetime.now(timezone.utc).isoformat()])
    metadata.append(["Timezone", "UTC"])
    metadata.append(["Filter From", start_at.isoformat()])
    metadata.append(["Filter To", end_at.isoformat()])
    metadata.append(["Room Filter", ",".join(map(str, room_numbers or []))])
    metadata.append(["Group Filter", ",".join(groups or [])])

    session.add(
        ReportDownload(
            requested_by_user_id=generated_by.id,
            from_at=start_at,
            to_at=end_at,
            room_filter={"rooms": room_numbers, "groups": groups, "include_alerts": include_alerts, "include_faults": include_faults},
            file_format="xlsx",
        )
    )

    output = BytesIO()
    workbook.save(output)
    output.seek(0)
    return output
